name: Release Client Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-packages:
    name: Build Packages and Create Release
    uses: ./.github/workflows/shared-release.yml

  publish-client:
    name: Publish Client Package to PyPI
    runs-on: ubuntu-latest
    needs: build-packages
    
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-packages
          path: dist/

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install twine
        run: pip install twine

      - name: Publish client package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_CLIENT_TOKEN }}
        run: |
          twine upload dist/chaukas_spec_client-*