name: Release Server Package

on:
  workflow_dispatch:
    inputs:
      client_run_id:
        description: 'Run ID of the client workflow that built the packages'
        required: true
        type: string
      artifact_name:
        description: 'Name of the artifact containing the packages'
        required: true
        type: string

jobs:
  publish-server:
    name: Publish Server Package to PyPI
    runs-on: ubuntu-latest
    
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist/
          run-id: ${{ inputs.client_run_id }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install twine
        run: pip install twine

      - name: Publish server package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_SERVER_TOKEN }}
        run: |
          twine upload dist/chaukas_spec_server-*