name: Release Client Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-client:
    name: Release Client Package
    uses: ./.github/workflows/shared-release.yml
    with:
      package_type: client
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_CLIENT_TOKEN }}